# heldino-stack.yml
# Configuration Docker Swarm pour l'application heldino.com (Laravel avec Filament)
# Le réseau 'app-network' sera créé et géré par Docker Swarm.

version: '3.8'

services:
  # Service Nginx: Reverse proxy et serveur web pour heldino.com
  nginx-heldino:
    image: nginx:1.22-alpine
    ports:
      - "8080:80"      # Port HTTP différent pour éviter les conflits
      - "8443:443"     # Port HTTPS différent pour éviter les conflits
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf           # Fichier de configuration principal Nginx
      - ./nginx/:/etc/nginx/conf.d/                # Fichiers de configuration des virtual hosts
      - heldino-app-data:/var/www/html             # Volume partagé pour les fichiers de l'application
    depends_on:
      - php-heldino                                # Dépend du service PHP pour le traitement des requêtes PHP-FPM
    networks:
      - heldino-network                            # Connecté au réseau applicatif

  # Service PHP-FPM: Exécute le code de l'application Laravel/PHP heldino.com
  php-heldino:
    image: ghcr.io/andriamihajaheldino/heldino.com:main # Image de l'application heldino.com
    volumes:
      - heldino-app-data:/var/www/html             # Volume partagé contenant le code source et les assets
      - ./storage/:/var/www/html/storage           # Monte le dossier storage local (logs, cache, sessions)
      - ./php.ini:/usr/local/etc/php/php.ini       # Configuration PHP personnalisée
    networks:
      - heldino-network                            # Connecté au réseau applicatif
    # Pas de 'ports' exposés car Nginx communique via le réseau interne

  # Service Redis: Cache (optionnel, peut être supprimé si pas utilisé)
  redis-heldino:
    image: redis:4.0
    ports:
      - "6383:6379"                                # Expose Redis sur le port 6383 de l'hôte (différent des autres apps)
    networks:
      - heldino-network                            # Connecté au réseau applicatif

# Définition des volumes persistants gérés par Swarm
volumes:
  heldino-app-data:       # Volume pour le code partagé entre Nginx et PHP
                          # Contient principalement les uploads et fichiers générés

# Définition des réseaux gérés par Swarm
networks:
  heldino-network:
    driver: overlay  # Driver requis pour la communication entre conteneurs sur différents nœuds Swarm